export const deptCols = [
    { key: "departmentType", label: "Department Type" },
    { key: "organizationType", label: "Organization Type" },
    { key: "departmentName", label: "Department Name" },
    { key: "parentDepartmentName", label: "Parent Department Name" },
    { key: "organizationCode", label: "Organization Code" },
    { key: "sector", label: "Sector" },
    { key: "status", label: "Status" }
]

export const deptData = [
    {
        departmentType: "Government",
        organizationType: "Ministry",
        departmentName: "Ministry of Finance",
        parentDepartmentName: "CPGRAMS",
        organizationCode: "MoRD",
        sector: "Finance",
        status: "Active",
    },
    {
        departmentType: "Government",
        organizationType: "Ministry",
        departmentName: "Ministry of Finance",
        parentDepartmentName: "CPGRAMS",
        organizationCode: "MoRD",
        sector: "Finance",
        status: "Inactive",
    },
    {
        departmentType: "Government",
        organizationType: "Ministry",
        departmentName: "Ministry of Finance",
        parentDepartmentName: "CPGRAMS",
        organizationCode: "MoRD",
        sector: "Finance",
        status: "Active",
    },
    {
        departmentType: "Government",
        organizationType: "Ministry",
        departmentName: "Ministry of Finance",
        parentDepartmentName: "CPGRAMS",
        organizationCode: "MoRD",
        sector: "Finance",
        status: "Active",
    },
    {
        departmentType: "Government",
        organizationType: "Ministry",
        departmentName: "Ministry of Finance",
        parentDepartmentName: "CPGRAMS",
        organizationCode: "MoRD",
        sector: "Finance",
        status: "Active",
    },
    {
        departmentType: "Government",
        organizationType: "Ministry",
        departmentName: "Ministry of Finance",
        parentDepartmentName: "CPGRAMS",
        organizationCode: "MoRD",
        sector: "Finance",
        status: "Active",
    },
    {
        departmentType: "Government",
        organizationType: "Ministry",
        departmentName: "Ministry of Finance",
        parentDepartmentName: "CPGRAMS",
        organizationCode: "MoRD",
        sector: "Finance",
        status: "Active",
    },
    {
        departmentType: "Government",
        organizationType: "Ministry",
        departmentName: "Ministry of Finance",
        parentDepartmentName: "CPGRAMS",
        organizationCode: "MoRD",
        sector: "Finance",
        status: "Active",
    },
    {
        departmentType: "Government",
        organizationType: "Ministry",
        departmentName: "Ministry of Finance",
        parentDepartmentName: "CPGRAMS",
        organizationCode: "MoRD",
        sector: "Finance",
        status: "Active",
    },
    {
        departmentType: "Government",
        organizationType: "Ministry",
        departmentName: "Ministry of Finance",
        parentDepartmentName: "CPGRAMS",
        organizationCode: "MoRD",
        sector: "Finance",
        status: "Active",
    },
    {
        departmentType: "Government",
        organizationType: "Ministry",
        departmentName: "Ministry of Finance",
        parentDepartmentName: "CPGRAMS",
        organizationCode: "MoRD",
        sector: "Finance",
        status: "Active",
    },
    {
        departmentType: "Government",
        organizationType: "Ministry",
        departmentName: "Ministry of Finance",
        parentDepartmentName: "CPGRAMS",
        organizationCode: "MoRD",
        sector: "Finance",
        status: "Active",
    },
    {
        departmentType: "Government",
        organizationType: "Ministry",
        departmentName: "Ministry of Finance",
        parentDepartmentName: "CPGRAMS",
        organizationCode: "MoRD",
        sector: "Finance",
        status: "Active",
    },
    {
        departmentType: "Government",
        organizationType: "Ministry",
        departmentName: "Ministry of Finance",
        parentDepartmentName: "CPGRAMS",
        organizationCode: "MoRD",
        sector: "Finance",
        status: "Active",
    },
    {
        departmentType: "Government",
        organizationType: "Ministry",
        departmentName: "Ministry of Finance",
        parentDepartmentName: "CPGRAMS",
        organizationCode: "MoRD",
        sector: "Finance",
        status: "Active",
    },
    {
        departmentType: "Government",
        organizationType: "Ministry",
        departmentName: "Ministry of Finance",
        parentDepartmentName: "CPGRAMS",
        organizationCode: "MoRD",
        sector: "Finance",
        status: "Active",
    },
    {
        departmentType: "Government",
        organizationType: "Ministry",
        departmentName: "Ministry of Finance",
        parentDepartmentName: "CPGRAMS",
        organizationCode: "MoRD",
        sector: "Finance",
        status: "Active",
    },
    {
        departmentType: "Government",
        organizationType: "Ministry",
        departmentName: "Ministry of Finance",
        parentDepartmentName: "CPGRAMS",
        organizationCode: "MoRD",
        sector: "Finance",
        status: "Active",
    },
    {
        departmentType: "Government",
        organizationType: "Ministry",
        departmentName: "Ministry of Finance",
        parentDepartmentName: "CPGRAMS",
        organizationCode: "MoRD",
        sector: "Finance",
        status: "Active",
    },
    {
        departmentType: "Government",
        organizationType: "Ministry",
        departmentName: "Ministry of Finance",
        parentDepartmentName: "CPGRAMS",
        organizationCode: "MoRD",
        sector: "Finance",
        status: "Active",
    },
    {
        departmentType: "Government",
        organizationType: "Ministry",
        departmentName: "Ministry of Finance",
        parentDepartmentName: "CPGRAMS",
        organizationCode: "MoRD",
        sector: "Finance",
        status: "Active",
    },
    {
        departmentType: "Government",
        organizationType: "Ministry",
        departmentName: "Ministry of Finance",
        parentDepartmentName: "CPGRAMS",
        organizationCode: "MoRD",
        sector: "Finance",
        status: "Active",
    },
    {
        departmentType: "Government",
        organizationType: "Ministry",
        departmentName: "Ministry of Finance",
        parentDepartmentName: "CPGRAMS",
        organizationCode: "MoRD",
        sector: "Finance",
        status: "Active",
    },
    {
        departmentType: "Government",
        organizationType: "Ministry",
        departmentName: "Ministry of Finance",
        parentDepartmentName: "CPGRAMS",
        organizationCode: "MoRD",
        sector: "Finance",
        status: "Active",
    },
    {
        departmentType: "Government",
        organizationType: "Ministry",
        departmentName: "Ministry of Finance",
        parentDepartmentName: "CPGRAMS",
        organizationCode: "MoRD",
        sector: "Finance",
        status: "Active",
    },
    {
        departmentType: "Government",
        organizationType: "Ministry",
        departmentName: "Ministry of Finance",
        parentDepartmentName: "CPGRAMS",
        organizationCode: "MoRD",
        sector: "Finance",
        status: "Active",
    },
    {
        departmentType: "Government",
        organizationType: "Ministry",
        departmentName: "Ministry of Finance",
        parentDepartmentName: "CPGRAMS",
        organizationCode: "MoRD",
        sector: "Finance",
        status: "Active",
    },
    {
        departmentType: "Government",
        organizationType: "Ministry",
        departmentName: "Ministry of Finance",
        parentDepartmentName: "CPGRAMS",
        organizationCode: "MoRD",
        sector: "Finance",
        status: "Active",
    },
    {
        departmentType: "Government",
        organizationType: "Ministry",
        departmentName: "Ministry of Finance",
        parentDepartmentName: "CPGRAMS",
        organizationCode: "MoRD",
        sector: "Finance",
        status: "Active",
    },
    {
        departmentType: "Government",
        organizationType: "Ministry",
        departmentName: "Ministry of Finance",
        parentDepartmentName: "CPGRAMS",
        organizationCode: "MoRD",
        sector: "Finance",
        status: "Active",
    },
    {
        departmentType: "Government",
        organizationType: "Ministry",
        departmentName: "Ministry of Finance",
        parentDepartmentName: "CPGRAMS",
        organizationCode: "MoRD",
        sector: "Finance",
        status: "Active",
    },
    {
        departmentType: "Government",
        organizationType: "Ministry",
        departmentName: "Ministry of Finance",
        parentDepartmentName: "CPGRAMS",
        organizationCode: "MoRD",
        sector: "Finance",
        status: "Active",
    },
    {
        departmentType: "Government",
        organizationType: "Ministry",
        departmentName: "Ministry of Finance",
        parentDepartmentName: "CPGRAMS",
        organizationCode: "MoRD",
        sector: "Finance",
        status: "Active",
    },
    {
        departmentType: "Government",
        organizationType: "Ministry",
        departmentName: "Ministry of Finance",
        parentDepartmentName: "CPGRAMS",
        organizationCode: "MoRD",
        sector: "Finance",
        status: "Active",
    },
    {
        departmentType: "Government",
        organizationType: "Ministry",
        departmentName: "Ministry of Finance",
        parentDepartmentName: "CPGRAMS",
        organizationCode: "MoRD",
        sector: "Finance",
        status: "Active",
    },
    {
        departmentType: "Government",
        organizationType: "Ministry",
        departmentName: "Ministry of Finance",
        parentDepartmentName: "CPGRAMS",
        organizationCode: "MoRD",
        sector: "Finance",
        status: "Active",
    },
    {
        departmentType: "Government",
        organizationType: "Ministry",
        departmentName: "Ministry of Finance",
        parentDepartmentName: "CPGRAMS",
        organizationCode: "MoRD",
        sector: "Finance",
        status: "Active",
    },
    {
        departmentType: "Government",
        organizationType: "Ministry",
        departmentName: "Ministry of Finance",
        parentDepartmentName: "CPGRAMS",
        organizationCode: "MoRD",
        sector: "Finance",
        status: "Active",
    },
    {
        departmentType: "Government",
        organizationType: "Ministry",
        departmentName: "Ministry of Finance",
        parentDepartmentName: "CPGRAMS",
        organizationCode: "MoRD",
        sector: "Finance",
        status: "Active",
    },
    {
        departmentType: "Government",
        organizationType: "Ministry",
        departmentName: "Ministry of Finance",
        parentDepartmentName: "CPGRAMS",
        organizationCode: "MoRD",
        sector: "Finance",
        status: "Active",
    },
    {
        departmentType: "Government",
        organizationType: "Ministry",
        departmentName: "Ministry of Finance",
        parentDepartmentName: "CPGRAMS",
        organizationCode: "MoRD",
        sector: "Finance",
        status: "Active",
    },
    {
        departmentType: "Government",
        organizationType: "Ministry",
        departmentName: "Ministry of Finance",
        parentDepartmentName: "CPGRAMS",
        organizationCode: "MoRD",
        sector: "Finance",
        status: "Active",
    },
    {
        departmentType: "Government",
        organizationType: "Ministry",
        departmentName: "Ministry of Finance",
        parentDepartmentName: "CPGRAMS",
        organizationCode: "MoRD",
        sector: "Finance",
        status: "Active",
    },
    {
        departmentType: "Government",
        organizationType: "Ministry",
        departmentName: "Ministry of Finance",
        parentDepartmentName: "CPGRAMS",
        organizationCode: "MoRD",
        sector: "Finance",
        status: "Active",
    },
    {
        departmentType: "Government",
        organizationType: "Ministry",
        departmentName: "Ministry of Finance",
        parentDepartmentName: "CPGRAMS",
        organizationCode: "MoRD",
        sector: "Finance",
        status: "Active",
    },
    {
        departmentType: "Government",
        organizationType: "Ministry",
        departmentName: "Ministry of Finance",
        parentDepartmentName: "CPGRAMS",
        organizationCode: "MoRD",
        sector: "Finance",
        status: "Active",
    },
    {
        departmentType: "Government",
        organizationType: "Ministry",
        departmentName: "Ministry of Finance",
        parentDepartmentName: "CPGRAMS",
        organizationCode: "MoRD",
        sector: "Finance",
        status: "Active",
    },
    {
        departmentType: "Government",
        organizationType: "Ministry",
        departmentName: "Ministry of Finance",
        parentDepartmentName: "CPGRAMS",
        organizationCode: "MoRD",
        sector: "Finance",
        status: "Active",
    },
    {
        departmentType: "Government",
        organizationType: "Ministry",
        departmentName: "Ministry of Finance",
        parentDepartmentName: "CPGRAMS",
        organizationCode: "MoRD",
        sector: "Finance",
        status: "Active",
    },
    {
        departmentType: "Government",
        organizationType: "Ministry",
        departmentName: "Ministry of Finance",
        parentDepartmentName: "CPGRAMS",
        organizationCode: "MoRD",
        sector: "Finance",
        status: "Active",
    },
    {
        departmentType: "Government",
        organizationType: "Ministry",
        departmentName: "Ministry of Finance",
        parentDepartmentName: "CPGRAMS",
        organizationCode: "MoRD",
        sector: "Finance",
        status: "Active",
    },
    {
        departmentType: "Government",
        organizationType: "Ministry",
        departmentName: "Ministry of Finance",
        parentDepartmentName: "CPGRAMS",
        organizationCode: "MoRD",
        sector: "Finance",
        status: "Active",
    },
    {
        departmentType: "Government",
        organizationType: "Ministry",
        departmentName: "Ministry of Finance",
        parentDepartmentName: "CPGRAMS",
        organizationCode: "MoRD",
        sector: "Finance",
        status: "Active",
    },
    {
        departmentType: "Government",
        organizationType: "Ministry",
        departmentName: "Ministry of Finance",
        parentDepartmentName: "CPGRAMS",
        organizationCode: "MoRD",
        sector: "Finance",
        status: "Active",
    },
    {
        departmentType: "Government",
        organizationType: "Ministry",
        departmentName: "Ministry of Finance",
        parentDepartmentName: "CPGRAMS",
        organizationCode: "MoRD",
        sector: "Finance",
        status: "Active",
    },
    {
        departmentType: "Government",
        organizationType: "Ministry",
        departmentName: "Ministry of Finance",
        parentDepartmentName: "CPGRAMS",
        organizationCode: "MoRD",
        sector: "Finance",
        status: "Active",
    },
    {
        departmentType: "Government",
        organizationType: "Ministry",
        departmentName: "Ministry of Finance",
        parentDepartmentName: "CPGRAMS",
        organizationCode: "MoRD",
        sector: "Finance",
        status: "Active",
    },
    {
        departmentType: "Government",
        organizationType: "Ministry",
        departmentName: "Ministry of Finance",
        parentDepartmentName: "CPGRAMS",
        organizationCode: "MoRD",
        sector: "Finance",
        status: "Active",
    },
    {
        departmentType: "Government",
        organizationType: "Ministry",
        departmentName: "Ministry of Finance",
        parentDepartmentName: "CPGRAMS",
        organizationCode: "MoRD",
        sector: "Finance",
        status: "Active",
    },
    {
        departmentType: "Government",
        organizationType: "Ministry",
        departmentName: "Ministry of Finance",
        parentDepartmentName: "CPGRAMS",
        organizationCode: "MoRD",
        sector: "Finance",
        status: "Active",
    },
    {
        departmentType: "Government",
        organizationType: "Ministry",
        departmentName: "Ministry of Finance",
        parentDepartmentName: "CPGRAMS",
        organizationCode: "MoRD",
        sector: "Finance",
        status: "Active",
    },
    {
        departmentType: "Government",
        organizationType: "Ministry",
        departmentName: "Ministry of Finance",
        parentDepartmentName: "CPGRAMS",
        organizationCode: "MoRD",
        sector: "Finance",
        status: "Active",
    },
    {
        departmentType: "Government",
        organizationType: "Ministry",
        departmentName: "Ministry of Finance",
        parentDepartmentName: "CPGRAMS",
        organizationCode: "MoRD",
        sector: "Finance",
        status: "Active",
    },
    {
        departmentType: "Government",
        organizationType: "Ministry",
        departmentName: "Ministry of Finance",
        parentDepartmentName: "CPGRAMS",
        organizationCode: "MoRD",
        sector: "Finance",
        status: "Active",
    },
    {
        departmentType: "Government",
        organizationType: "Ministry",
        departmentName: "Ministry of Finance",
        parentDepartmentName: "CPGRAMS",
        organizationCode: "MoRD",
        sector: "Finance",
        status: "Active",
    },
    {
        departmentType: "Government",
        organizationType: "Ministry",
        departmentName: "Ministry of Finance",
        parentDepartmentName: "CPGRAMS",
        organizationCode: "MoRD",
        sector: "Finance",
        status: "Active",
    },
    {
        departmentType: "Government",
        organizationType: "Ministry",
        departmentName: "Ministry of Finance",
        parentDepartmentName: "CPGRAMS",
        organizationCode: "MoRD",
        sector: "Finance",
        status: "Active",
    },
    {
        departmentType: "Government",
        organizationType: "Ministry",
        departmentName: "Ministry of Finance",
        parentDepartmentName: "CPGRAMS",
        organizationCode: "MoRD",
        sector: "Finance",
        status: "Active",
    },
    {
        departmentType: "Government",
        organizationType: "Ministry",
        departmentName: "Ministry of Finance",
        parentDepartmentName: "CPGRAMS",
        organizationCode: "MoRD",
        sector: "Finance",
        status: "Active",
    },
    {
        departmentType: "Government",
        organizationType: "Ministry",
        departmentName: "Ministry of Finance",
        parentDepartmentName: "CPGRAMS",
        organizationCode: "MoRD",
        sector: "Finance",
        status: "Active",
    },
    {
        departmentType: "Government",
        organizationType: "Ministry",
        departmentName: "Ministry of Finance",
        parentDepartmentName: "CPGRAMS",
        organizationCode: "MoRD",
        sector: "Finance",
        status: "Active",
    },
    {
        departmentType: "Government",
        organizationType: "Ministry",
        departmentName: "Ministry of Finance",
        parentDepartmentName: "CPGRAMS",
        organizationCode: "MoRD",
        sector: "Finance",
        status: "Active",
    },
    {
        departmentType: "Government",
        organizationType: "Ministry",
        departmentName: "Ministry of Finance",
        parentDepartmentName: "CPGRAMS",
        organizationCode: "MoRD",
        sector: "Finance",
        status: "Active",
    },
    {
        departmentType: "Government",
        organizationType: "Ministry",
        departmentName: "Ministry of Finance",
        parentDepartmentName: "CPGRAMS",
        organizationCode: "MoRD",
        sector: "Finance",
        status: "Active",
    },
    {
        departmentType: "Government",
        organizationType: "Ministry",
        departmentName: "Ministry of Finance",
        parentDepartmentName: "CPGRAMS",
        organizationCode: "MoRD",
        sector: "Finance",
        status: "Active",
    },
    {
        departmentType: "Government",
        organizationType: "Ministry",
        departmentName: "Ministry of Finance",
        parentDepartmentName: "CPGRAMS",
        organizationCode: "MoRD",
        sector: "Finance",
        status: "Active",
    },
    {
        departmentType: "Government",
        organizationType: "Ministry",
        departmentName: "Ministry of Finance",
        parentDepartmentName: "CPGRAMS",
        organizationCode: "MoRD",
        sector: "Finance",
        status: "Active",
    },
]